name: GO CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build Docker Image
    #   run: |
    #    cd go
    #    docker build -t myapp-go .

  deploy:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    needs: build
    environment: Staging
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push Docker Image
    #   run: |
    #     docker tag myapp-go ramdas1999/myapp-go:latest
    #     docker push ramdas1999/myapp-go:latest

    - name: Deploy to Staging
      run: |
           pwd
           # cd go
           # docker-compose up
           

           
