name: NEXTJS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
       cd nextjs
       docker build -t myapp-nextjs .
       
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Staging
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag myapp-nextjs ramdas1999/myapp-nextjs:latest
        docker push ramdas1999/myapp-nextjs:latest

    - name: Deploy to Staging
      run: |
            cd nextjs
            docker-compose up
